// Generated PNG icons (build-safe — no native icon-font dependency).
export const ICONS = {
  locGray: require('./assets/loc-gray.png'),
  locMuted: require('./assets/loc-muted.png'),
  locWhite: require('./assets/loc-white.png'),
  search: require('./assets/search.png'),
  searchMuted: require('./assets/search-muted.png'),
  filter: require('./assets/filter.png'),
  cardGradient: require('./assets/card-gradient.png'),
  logoWhite: require('./assets/logo-white.png'),
  groups: require('./assets/glyph-groups.png'),
  compass: require('./assets/glyph-compass.png'),
  navHome: require('./assets/nav-home.png'),
  navSearch: require('./assets/nav-search.png'),
  navExp: require('./assets/nav-exp.png'),
  navInbox: require('./assets/nav-inbox.png'),
  navProfile: require('./assets/nav-profile.png'),
  bell: require('./assets/bell.png'),
  clock: require('./assets/clock.png'),
  people: require('./assets/ic-people.png'),
  share: require('./assets/ic-share.png'),
  heart: require('./assets/ic-heart.png'),
  heartFill: require('./assets/ic-heart-fill.png'),
  check: require('./assets/ic-check.png'),
  calendar: require('./assets/ic-calendar.png'),
  card: require('./assets/ic-card.png'),
  globe: require('./assets/ic-globe.png'),
  shield: require('./assets/ic-shield.png'),
  arrowRight: require('./assets/ic-arrowright.png'),
};
